services:
  web:
    build:
      context: .
      dockerfile: DockerFile
    container_name: amnesty-collab-web
    env_file:
      - .env.example
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - django_sqlite_data:/app/data
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped

volumes:
  django_sqlite_data:
